### ISSUE TITLE
Implement a `login` Github Action

### ISSUE THREAD

**Issue by carlspring** [carlspring/mend-actions#2]
# Task Description

We need to implement a Github Action that handles the authentication.

# Open Questions

# Notes

# Task List

The following tasks will need to be carried out:
* [x] Investigate what needs to be done.
* [x] Provide a solution.
* [x] Test the fix.
  * [x] [Test workflow](https://github.com/carlspring/mend-actions/blob/master/.github/workflows/test-login.yml).
  * [x] [Test action](https://github.com/carlspring/mend-actions/actions/workflows/test-login.yml).
* [ ] Update the documentation.

# Task Relationships

This task:
* Is a sub-task of:
* Depends on:
  * #1 
* Is a follow-up of:
* Relates to:

# Resources

# Useful Links

# Points of Contact

**Comment by carlspring** [comment]
Implemented.
