### ISSUE TITLE
Implement a `scan-docker` Github Action

### ISSUE THREAD

**Issue by carlspring** [carlspring/mend-actions#3]
# Task Description

We need to implement a Github action for scanning Docker images using the Mend.io CLI.

# Open Questions

* Should we also look into source code analysis?

# Notes

# Task List

The following tasks will need to be carried out:
* [x] nvestigate what needs to be done.
* [x] Provide a solution.
* [ ] Test the fix.
  * [x] [Test workflow](https://github.com/carlspring/mend-actions/blob/master/.github/workflows/test-scan.yml).
  * [x] [Test action](https://github.com/carlspring/mend-actions/actions/workflows/test-scan.yml).
  * [x] Mend.io Cloud Native contains the reports
  ![image](https://github.com/user-attachments/assets/be0ae9fd-81d0-4fff-97f7-8f7fd394042f)
   * [ ] The reports are succesfully fed into Github Advanced Security (GHAS).

# Task Relationships

This task:
* Is a sub-task of:
* Depends on:
  * #1 
  * #2
* Is a follow-up of:
* Relates to:

# Resources

# Useful Links

# Points of Contact
